import type { LucideIcon } from "lucide-react";
import {
  Baby,
  Banknote,
  BedDouble,
  Briefcase,
  Car,
  CircleDot,
  Clapperboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Droplets,
  Film,
  Flame,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  Home,
  Landmark,
  Music2,
  Package,
  PawPrint,
  PiggyBank,
  Plane,
  PlayCircle,
  Receipt,
  Repeat,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  TrendingUp,
  Utensils,
  Wifi,
  Zap,
} from "lucide-react";

const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  "shopping-cart": ShoppingCart,
  coffee: Coffee,
  car: Car,
  fuel: Fuel,
  "shopping-bag": ShoppingBag,
  home: Home,
  zap: Zap,
  droplets: Droplets,
  flame: Flame,
  wifi: Wifi,
  smartphone: Smartphone,
  receipt: Receipt,
  "music-2": Music2,
  "play-circle": PlayCircle,
  clapperboard: Clapperboard,
  package: Package,
  repeat: Repeat,
  film: Film,
  "gamepad-2": Gamepad2,
  "heart-pulse": HeartPulse,
  dumbbell: Dumbbell,
  "graduation-cap": GraduationCap,
  plane: Plane,
  "bed-double": BedDouble,
  gift: Gift,
  sparkles: Sparkles,
  shield: Shield,
  "credit-card": CreditCard,
  "heart-handshake": HeartHandshake,
  "paw-print": PawPrint,
  baby: Baby,
  briefcase: Briefcase,
  landmark: Landmark,
  "trending-up": TrendingUp,
  banknote: Banknote,
  "piggy-bank": PiggyBank,
  "circle-dot": CircleDot,
};

export function getCategoryLucideIcon(iconName: string): LucideIcon {
  const key = iconName.trim().toLowerCase();
  return CATEGORY_ICON_MAP[key] ?? CircleDot;
}

export const CATEGORY_ICON_NAMES = Object.keys(CATEGORY_ICON_MAP);
