abstract final class AppRoutes {
  static const onboarding = '/onboarding';
  static const home = '/';
  static const expenses = '/expenses';
  static const expenseAdd = '/expenses/add';
  static const insights = '/insights';
  static const jithu = '/jithu';
  static const more = '/more';
  static const salary = '/salary';
  static const subscriptions = '/subscriptions';
  static const loans = '/loans';
  static const borrowed = '/borrowed';
  static const settings = '/settings';
  static const budget = '/budget';
  static const budgetSetup = '/budget/setup';
  static const budgetAlerts = '/budget/alerts';
  static const search = '/search';
  static const activityHistory = '/activity';
  static const recycleBin = '/recycle-bin';
  static const about = '/about';
  static const helpSupport = '/help';
  static const auth = '/auth';
}
